name: example
description: "A download_transformer example."
version: 0.0.1

environment:
  sdk: '>=3.7.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  download_transformer:
    path: ../

flutter:
  assets:
    - path: assets/texture_sample.png
      transformers:
        - package: download_transformer
    - path: assets/to_download/
      transformers:
        - package: download_transformer