name: download_transformer
description: A dart transformer for downloading assets. This is useful, if you don't have to check in large assets or want to pull assets from a directory shared with non-programmers.
repository: https://github.com/bvoq/download_transformer
version: 1.0.0

environment:
  # support for asset transformers started with 3.7.0
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  args: ^2.4.0
  http: ^1.0.0

dev_dependencies:
  crypto: ^3.0.6
  test: ^1.24.0
